# Generated by Django 4.0.4 on 2022-05-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageAlbum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='author',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
