# Generated by Django 4.0.4 on 2022-06-06 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageAlbum', '0002_alter_album_media_alter_author_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='media',
            new_name='images',
        ),
    ]
