# Generated by Django 4.0.4 on 2022-06-06 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageAlbum', '0003_rename_media_album_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='script',
            new_name='description',
        ),
    ]
